{
  "sksl": {
    "entrypoint": "crt_barrel_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uStrength;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 centered = (uv * 2.0) - vec2(1.0);\n    float r2 = dot(centered, centered);\n    vec2 warped = centered * (1.0 + (uStrength * r2));\n    vec2 srcUv = (warped * 0.5) + vec2(0.5);\n    vec4 sampled = uTexture.eval(uTexture_size * ( clamp(srcUv, vec2(0.0), vec2(1.0))));\n    float inBounds = ((step(0.0, srcUv.x) * step(srcUv.x, 1.0)) * step(0.0, srcUv.y)) * step(srcUv.y, 1.0);\n    fragColor = mix(vec4(0.0, 0.0, 0.0, 1.0), sampled, vec4(inBounds));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uStrength",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 2,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}